# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VectorStoreArgs', 'VectorStore']

@pulumi.input_type
class VectorStoreArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 api_key: Optional[pulumi.Input[str]] = None,
                 chunking_strategy: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 expires_after: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 file_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None):
        """
        The set of arguments for constructing a VectorStore resource.
        :param pulumi.Input[str] name: The name of the vector store.
        :param pulumi.Input[str] api_key: Optional OpenAI API key to use for this specific resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] chunking_strategy: The chunking strategy used to chunk files.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] expires_after: The expiration policy for the vector store.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] file_ids: A list of file IDs to be used in the vector store.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] metadata: Set of key-value pairs that can be used to store additional information about the vector store.
        """
        pulumi.set(__self__, "name", name)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if chunking_strategy is not None:
            pulumi.set(__self__, "chunking_strategy", chunking_strategy)
        if expires_after is not None:
            pulumi.set(__self__, "expires_after", expires_after)
        if file_ids is not None:
            pulumi.set(__self__, "file_ids", file_ids)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        The name of the vector store.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[str]]:
        """
        Optional OpenAI API key to use for this specific resource.
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "api_key", value)

    @property
    @pulumi.getter(name="chunkingStrategy")
    def chunking_strategy(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        The chunking strategy used to chunk files.
        """
        return pulumi.get(self, "chunking_strategy")

    @chunking_strategy.setter
    def chunking_strategy(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "chunking_strategy", value)

    @property
    @pulumi.getter(name="expiresAfter")
    def expires_after(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        The expiration policy for the vector store.
        """
        return pulumi.get(self, "expires_after")

    @expires_after.setter
    def expires_after(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "expires_after", value)

    @property
    @pulumi.getter(name="fileIds")
    def file_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        A list of file IDs to be used in the vector store.
        """
        return pulumi.get(self, "file_ids")

    @file_ids.setter
    def file_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "file_ids", value)

    @property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Set of key-value pairs that can be used to store additional information about the vector store.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "metadata", value)


class VectorStore(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: Optional[pulumi.Input[str]] = None,
                 chunking_strategy: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 expires_after: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 file_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a VectorStore resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] api_key: Optional OpenAI API key to use for this specific resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] chunking_strategy: The chunking strategy used to chunk files.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] expires_after: The expiration policy for the vector store.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] file_ids: A list of file IDs to be used in the vector store.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] metadata: Set of key-value pairs that can be used to store additional information about the vector store.
        :param pulumi.Input[str] name: The name of the vector store.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VectorStoreArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VectorStore resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param VectorStoreArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VectorStoreArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: Optional[pulumi.Input[str]] = None,
                 chunking_strategy: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 expires_after: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 file_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VectorStoreArgs.__new__(VectorStoreArgs)

            __props__.__dict__["api_key"] = None if api_key is None else pulumi.Output.secret(api_key)
            __props__.__dict__["chunking_strategy"] = chunking_strategy
            __props__.__dict__["expires_after"] = expires_after
            __props__.__dict__["file_ids"] = file_ids
            __props__.__dict__["metadata"] = metadata
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["created_at"] = None
            __props__.__dict__["expires_at"] = None
            __props__.__dict__["file_count_cancelled"] = None
            __props__.__dict__["file_counts"] = None
            __props__.__dict__["id"] = None
            __props__.__dict__["last_active_at"] = None
            __props__.__dict__["object"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["usage_bytes"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(VectorStore, __self__).__init__(
            'openai:index:VectorStore',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'VectorStore':
        """
        Get an existing VectorStore resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = VectorStoreArgs.__new__(VectorStoreArgs)

        __props__.__dict__["api_key"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["expires_after"] = None
        __props__.__dict__["expires_at"] = None
        __props__.__dict__["file_count_cancelled"] = None
        __props__.__dict__["file_counts"] = None
        __props__.__dict__["file_ids"] = None
        __props__.__dict__["id"] = None
        __props__.__dict__["last_active_at"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["object"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["usage_bytes"] = None
        return VectorStore(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[Optional[str]]:
        """
        Optional OpenAI API key used for this specific resource.
        """
        return pulumi.get(self, "api_key")

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[float]:
        """
        The Unix timestamp (in seconds) for when the vector store was created.
        """
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter(name="expiresAfter")
    def expires_after(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        The expiration policy for the vector store.
        """
        return pulumi.get(self, "expires_after")

    @property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[float]]:
        """
        The Unix timestamp (in seconds) for when the vector store will expire.
        """
        return pulumi.get(self, "expires_at")

    @property
    @pulumi.getter(name="fileCountCancelled")
    def file_count_cancelled(self) -> pulumi.Output[Optional[float]]:
        """
        The number of cancelled files in this vector store.
        """
        return pulumi.get(self, "file_count_cancelled")

    @property
    @pulumi.getter(name="fileCounts")
    def file_counts(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        Counts of files in the vector store by status.
        """
        return pulumi.get(self, "file_counts")

    @property
    @pulumi.getter(name="fileIds")
    def file_ids(self) -> pulumi.Output[Optional[Sequence[str]]]:
        """
        A list of file IDs used in the vector store.
        """
        return pulumi.get(self, "file_ids")

    @property
    @pulumi.getter
    def id(self) -> pulumi.Output[str]:
        """
        The unique identifier for the vector store.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="lastActiveAt")
    def last_active_at(self) -> pulumi.Output[Optional[float]]:
        """
        The Unix timestamp (in seconds) for when the vector store was last active.
        """
        return pulumi.get(self, "last_active_at")

    @property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        Set of key-value pairs that can be used to store additional information about the vector store.
        """
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The name of the vector store.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def object(self) -> pulumi.Output[str]:
        """
        The object type, which is always 'vector_store'.
        """
        return pulumi.get(self, "object")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        """
        The status of the vector store (e.g., 'completed', 'in_progress').
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="usageBytes")
    def usage_bytes(self) -> pulumi.Output[Optional[float]]:
        """
        The number of bytes used by the vector store.
        """
        return pulumi.get(self, "usage_bytes")

