// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AssistantArgs } from "./assistant";
export type Assistant = import("./assistant").Assistant;
export const Assistant: typeof import("./assistant").Assistant = null as any;
utilities.lazyLoad(exports, ["Assistant"], () => require("./assistant"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { VectorStoreArgs } from "./vectorStore";
export type VectorStore = import("./vectorStore").VectorStore;
export const VectorStore: typeof import("./vectorStore").VectorStore = null as any;
utilities.lazyLoad(exports, ["VectorStore"], () => require("./vectorStore"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "openai:index:Assistant":
                return new Assistant(name, <any>undefined, { urn })
            case "openai:index:VectorStore":
                return new VectorStore(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("openai", "index", _module)
pulumi.runtime.registerResourcePackage("openai", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:openai") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
